/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./../layouts/DefaultLayout.vue')['default']
    DefaultLayoutContent: typeof import('./../layouts/DefaultLayout/DefaultLayoutContent.vue')['default']
    DefaultLayoutHeader: typeof import('./../layouts/DefaultLayout/DefaultLayoutHeader.vue')['default']
    DefaultLayoutSider: typeof import('./../layouts/DefaultLayout/DefaultLayoutSider.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    NaiveWrapper: typeof import('./../components/NaiveWrapper.vue')['default']
    NavigationMenu: typeof import('./../components/NavigationMenu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
